version: '3.8'
services:
    postgres:
        image: postgres:15
        environment:
            - POSTGRES_USER=postgres # replace with correct user
            - POSTGRES_PASSWORD=password # replace with correct password
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - postgres-db-network
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'user@foo.com' # replace with correct user
            PGADMIN_DEFAULT_PASSWORD: 'password' # replace with correct password
        ports:
            - 8081:80
        volumes:
            - ./servers.json:/pgadmin4/servers.json
            - ./pgpass:/pgadmin4/pgpass
            - pgadmin-volume:/var/lib/pgadmin
        networks:
            - postgres-db-network
      
    dozzle: # monitor docker output
        container_name: dozzle
        image: amir20/dozzle:latest
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 9999:8080

volumes:
    postgres-db-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data
    pgadmin-volume:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./pgadmin
networks:
    postgres-db-network:
        driver: bridge